"""add schedule_days to habit

Revision ID: d1eccf37e38a
Revises: 76cca2072cb6
Create Date: 2026-04-29 13:57:09.661668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1eccf37e38a'
down_revision: Union[str, Sequence[str], None] = '76cca2072cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('schedule_days', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'schedule_days')
    # ### end Alembic commands ###
